2022-11-09 09:44:27,076 Converting data/part258/in/kerala/2015/2015_129_112.pdf to img...
2022-11-09 09:44:38,525 Parsing first and last page data..
2022-11-09 09:44:42,960 Detecting and parsing data/part258/in/kerala/2015/2015_129_112.pdf boxes..
2022-11-09 09:44:42,960 Processing page 3
2022-11-09 09:45:20,282 Processing page 4
2022-11-09 09:45:57,602 Processing page 5
2022-11-09 09:46:35,277 Processing page 6
2022-11-09 09:47:12,174 Processing page 7
2022-11-09 09:47:49,327 Processing page 8
2022-11-09 09:48:25,917 Processing page 9
2022-11-09 09:49:03,267 Processing page 10
2022-11-09 09:49:40,426 Processing page 11
2022-11-09 09:50:18,280 Processing page 12
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d35\u0d3f Piprey| reel | [=e OrderedDict([('number', '299'), ('id', 'KL/19/133/309205'), ('\u0d2a\u0d47\u0d30\u0d4d', 'dew'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d2e\u0d4b\u0d39\u0d28\u0d28\u0d4d\\u200d \u0d1a\u0d46\u0d1f\u0d4d\u0d1f\u0d3f\u0d2f\u0d3e\u0d30\u0d4d\\u200d')])"
Arguments: ()
2022-11-09 09:50:21,406 Split uncaught \u0d35\u0d3f Piprey| reel | [=e OrderedDict([('number', '299'), ('id', 'KL/19/133/309205'), ('\u0d2a\u0d47\u0d30\u0d4d', 'dew'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', '\u0d2e\u0d4b\u0d39\u0d28\u0d28\u0d4d\u200d \u0d1a\u0d46\u0d1f\u0d4d\u0d1f\u0d3f\u0d2f\u0d3e\u0d30\u0d4d\u200d')])
2022-11-09 09:50:55,471 Processing page 13
2022-11-09 09:51:32,189 Processing page 14
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-40: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d35\u0d3f Piprey| reel | [=e OrderedDict([('number', 'RI)'), ('id', 'KL/19/133/309447'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d2c\u0d3f\u0d28\u0d4d\u0d26\u0d41'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '2/647 (0739)')])"
Arguments: ()
2022-11-09 09:51:35,114 Split uncaught \u0d35\u0d3f Piprey| reel | [=e OrderedDict([('number', 'RI)'), ('id', 'KL/19/133/309447'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d2c\u0d3f\u0d28\u0d4d\u0d26\u0d41'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '2/647 (0739)')])
2022-11-09 09:52:09,579 Processing page 15
2022-11-09 09:52:46,812 Processing page 16
2022-11-09 09:53:24,106 Processing page 17
2022-11-09 09:54:02,177 Processing page 18
2022-11-09 09:54:39,570 Processing page 19
2022-11-09 09:55:16,156 Processing page 20
2022-11-09 09:55:54,036 Processing page 21
2022-11-09 09:56:33,641 Processing page 22
2022-11-09 09:57:10,764 Processing page 23
2022-11-09 09:57:47,613 Processing page 24
2022-11-09 09:58:23,804 Processing page 25
2022-11-09 09:59:00,051 Processing page 26

#################
Epilogue Job Info:
Job ID: 467116[258].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-258
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:15:00,vmem=2234812kb,walltime=00:15:31,mem=1269384kb,energy_used=0
Exit Code: 271
#################

