2022-11-09 09:43:57,477 Converting data/part39/in/kerala/2015/2015_020_051.pdf to img...
2022-11-09 09:44:04,103 Parsing first and last page data..
2022-11-09 09:44:06,073 Detecting and parsing data/part39/in/kerala/2015/2015_020_051.pdf boxes..
2022-11-09 09:44:06,074 Processing page 3
2022-11-09 09:44:37,978 Processing page 4
2022-11-09 09:45:09,498 Processing page 5
2022-11-09 09:45:45,535 Processing page 6
2022-11-09 09:46:21,820 Processing page 7
2022-11-09 09:46:55,513 Processing page 8
2022-11-09 09:47:32,375 Processing page 9
2022-11-09 09:48:05,240 Processing page 10
2022-11-09 09:48:43,605 Processing page 11
2022-11-09 09:49:19,821 Processing page 12
2022-11-09 09:49:55,680 Processing page 13
2022-11-09 09:50:31,120 Processing page 14
2022-11-09 09:51:06,196 Processing page 15
2022-11-09 09:51:36,576 Processing page 16
2022-11-09 09:52:12,795 Processing page 17
2022-11-09 09:52:48,449 Processing page 18
2022-11-09 09:53:18,436 Processing page 19
2022-11-09 09:53:55,654 Processing page 20
2022-11-09 09:54:23,713 Processing page 21
2022-11-09 09:54:50,789 Processing page 22
2022-11-09 09:55:26,756 Processing page 23
2022-11-09 09:56:03,313 Processing page 24
2022-11-09 09:56:36,276 Processing page 25
2022-11-09 09:57:12,368 Processing page 26
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 118-121: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught sdomalog ete (Gle>JaIB OrderedDict([('number', '720'), ('id', 'BXN1338821'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d3f\u0d28\u0d4d\u0d27\u0d41')])"
Arguments: ()
2022-11-09 09:57:15,369 Split uncaught sdomalog ete (Gle>JaIB OrderedDict([('number', '720'), ('id', 'BXN1338821'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d3f\u0d28\u0d4d\u0d27\u0d41')])
2022-11-09 09:57:50,277 Processing page 27
2022-11-09 09:58:18,909 Processing page 28

#################
Epilogue Job Info:
Job ID: 467116[39].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-39
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:14:56,vmem=2319892kb,walltime=00:15:13,mem=1352484kb,energy_used=0
Exit Code: 271
#################

