2022-11-09 09:44:02,873 Converting data/part69/in/kerala/2015/2015_036_042.pdf to img...
2022-11-09 09:44:11,807 Parsing first and last page data..
2022-11-09 09:44:14,857 Detecting and parsing data/part69/in/kerala/2015/2015_036_042.pdf boxes..
2022-11-09 09:44:14,857 Processing page 3
2022-11-09 09:44:51,104 Processing page 4
2022-11-09 09:45:26,992 Processing page 5
2022-11-09 09:46:04,141 Processing page 6
2022-11-09 09:46:41,203 Processing page 7
2022-11-09 09:47:17,527 Processing page 8
2022-11-09 09:47:53,867 Processing page 9
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 121-124: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught ANgynmue 3/553 @ELst=10)) OrderedDict([('number', '209'), ('id', 'THN0082115'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d28\u0d2b\u0d40\u0d38')])"
Arguments: ()
2022-11-09 09:47:56,814 Split uncaught ANgynmue 3/553 @ELst=10)) OrderedDict([('number', '209'), ('id', 'THN0082115'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d28\u0d2b\u0d40\u0d38')])
2022-11-09 09:48:29,380 Processing page 10
2022-11-09 09:49:07,159 Processing page 11
2022-11-09 09:49:44,275 Processing page 12
2022-11-09 09:50:20,712 Processing page 13
2022-11-09 09:50:56,887 Processing page 14
2022-11-09 09:51:33,512 Processing page 15
2022-11-09 09:52:10,913 Processing page 16
2022-11-09 09:52:47,791 Processing page 17
2022-11-09 09:53:23,981 Processing page 18
2022-11-09 09:54:02,075 Processing page 19
2022-11-09 09:54:38,908 Processing page 20
2022-11-09 09:55:15,942 Processing page 21
2022-11-09 09:55:52,998 Processing page 22
2022-11-09 09:56:29,810 Processing page 23
2022-11-09 09:57:06,767 Processing page 24
2022-11-09 09:57:43,632 Processing page 25
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 119-126: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught Ngee AGEMIO@2Sle> OrderedDict([('number', '677'), ('id', 'KL/05/031/015481'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', 'granaase}s)'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '3/674 (11/810)')])"
Arguments: ()
2022-11-09 09:58:13,490 Split uncaught Ngee AGEMIO@2Sle> OrderedDict([('number', '677'), ('id', 'KL/05/031/015481'), ('\u0d05\u0d1a\u0d4d\u0d1b\u0d28\u0d4d\u0d31\u0d46 \u0d2a\u0d47\u0d30\u0d4d', 'granaase}s)'), ('\u0d35\u0d40\u0d1f\u0d4d\u0d1f\u0d41\u0d28\u0d2e\u0d4d\u0d2a\u0d30\u0d4d', '3/674 (11/810)')])
2022-11-09 09:58:21,269 Processing page 26
2022-11-09 09:58:58,452 Processing page 27

#################
Epilogue Job Info:
Job ID: 467116[69].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-69
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:14:55,vmem=2267084kb,walltime=00:15:16,mem=1305988kb,energy_used=0
Exit Code: 271
#################

