2022-11-09 09:44:02,839 Converting data/part73/in/kerala/2015/2015_038_038.pdf to img...
2022-11-09 09:44:09,336 Parsing first and last page data..
2022-11-09 09:44:12,301 Detecting and parsing data/part73/in/kerala/2015/2015_038_038.pdf boxes..
2022-11-09 09:44:12,301 Processing page 3
2022-11-09 09:44:47,370 Processing page 4
2022-11-09 09:45:22,199 Processing page 5
2022-11-09 09:45:57,438 Processing page 6
2022-11-09 09:46:33,497 Processing page 7
2022-11-09 09:47:09,979 Processing page 8
2022-11-09 09:47:45,501 Processing page 9
2022-11-09 09:48:22,332 Processing page 10
2022-11-09 09:48:57,651 Processing page 11
2022-11-09 09:49:34,153 Processing page 12
2022-11-09 09:50:10,602 Processing page 13
2022-11-09 09:50:46,885 Processing page 14
2022-11-09 09:51:24,235 Processing page 15
2022-11-09 09:52:00,792 Processing page 16
2022-11-09 09:52:36,238 Processing page 17
2022-11-09 09:52:45,155 Processing page 18
2022-11-09 09:53:19,981 Processing page 19
2022-11-09 09:53:55,266 Processing page 20
2022-11-09 09:54:32,205 Processing page 21
2022-11-09 09:55:09,236 Processing page 22
2022-11-09 09:55:46,466 Processing page 23
2022-11-09 09:56:22,661 Processing page 24
2022-11-09 09:56:58,552 Processing page 25
2022-11-09 09:57:35,201 Processing page 26
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2014' in position 56: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught aligned 10/90en ~\u2014= (2/381) OrderedDict([('number', '688'), ('id', 'NQM3309192'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d2f\u0d4d\u0d2b\u0d41\u0d28\u0d4d\u0d28\u0d40\u0d38')])"
Arguments: ()
2022-11-09 09:57:49,163 Split uncaught aligned 10/90en ~\u2014= (2/381) OrderedDict([('number', '688'), ('id', 'NQM3309192'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d38\u0d2f\u0d4d\u0d2b\u0d41\u0d28\u0d4d\u0d28\u0d40\u0d38')])
2022-11-09 09:58:13,110 Processing page 27
2022-11-09 09:58:49,456 Processing page 28

#################
Epilogue Job Info:
Job ID: 467116[73].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-73
Resource List: nodes=1:ppn=1,mem=3400mb,neednodes=1:ppn=1
Resources Used: cput=00:14:57,vmem=2276888kb,walltime=00:15:17,mem=1310120kb,energy_used=0
Exit Code: 271
#################

