2022-11-07 20:32:36,095 Converting data/part232/in/kerala/2015/2015_117_080.pdf to img...
2022-11-07 20:32:41,594 Parsing first and last page data..
2022-11-07 20:32:48,930 Detecting and parsing data/part232/in/kerala/2015/2015_117_080.pdf boxes..
2022-11-07 20:32:48,931 Processing page 3
2022-11-07 20:33:24,043 Processing page 4
2022-11-07 20:34:00,741 Processing page 5
2022-11-07 20:34:38,433 Processing page 6
2022-11-07 20:35:16,079 Processing page 7
2022-11-07 20:35:53,024 Processing page 8
2022-11-07 20:36:29,170 Processing page 9
2022-11-07 20:37:05,170 Processing page 10
2022-11-07 20:37:40,666 Processing page 11
2022-11-07 20:38:15,965 Processing page 12
2022-11-07 20:38:51,632 Processing page 13
2022-11-07 20:39:27,852 Processing page 14
2022-11-07 20:40:03,966 Processing page 15
2022-11-07 20:40:42,374 Processing page 16
2022-11-07 20:41:19,524 Processing page 17
2022-11-07 20:41:58,358 Processing page 18
2022-11-07 20:42:34,414 Processing page 19
2022-11-07 20:43:04,065 Processing page 20
2022-11-07 20:43:40,151 Processing page 21
2022-11-07 20:44:16,158 Processing page 22
2022-11-07 20:44:53,687 Processing page 23
2022-11-07 20:45:30,152 Processing page 24
2022-11-07 20:46:07,328 Processing page 25
2022-11-07 20:46:44,875 Processing page 26
2022-11-07 20:47:24,279 Processing page 27
2022-11-07 20:48:02,968 Processing page 28
2022-11-07 20:48:42,053 Processing page 29
2022-11-07 20:49:21,171 Processing page 30
2022-11-07 20:49:59,366 Processing page 31
2022-11-07 20:50:02,539 Processing page 32
2022-11-07 20:50:08,557 Processing page 33
2022-11-07 20:50:10,269 Processing page 34
2022-11-07 20:50:16,645 Processing page 35
2022-11-07 20:50:27,389 Processing page 36
2022-11-07 20:50:28,955 Processing page 37
2022-11-07 20:50:29,188 Processing page 38
2022-11-07 20:50:29,402 Processing page 39
2022-11-07 20:50:29,604 Formatting and exporting data/part232/in/kerala/2015/2015_117_080.pdf data..
2022-11-07 20:50:29,739 Converted to csv: data/out/kerala/2015/2015_117_080.csv
2022-11-07 20:50:29,756 Converting data/part232/in/kerala/2015/2015_117_081.pdf to img...
2022-11-07 20:50:36,220 Parsing first and last page data..
2022-11-07 20:50:41,922 Detecting and parsing data/part232/in/kerala/2015/2015_117_081.pdf boxes..
2022-11-07 20:50:41,923 Processing page 3
2022-11-07 20:51:18,509 Processing page 4
2022-11-07 20:51:55,816 Processing page 5
2022-11-07 20:52:31,875 Processing page 6
2022-11-07 20:53:07,683 Processing page 7
2022-11-07 20:53:44,189 Processing page 8
2022-11-07 20:54:21,058 Processing page 9
2022-11-07 20:54:57,992 Processing page 10
2022-11-07 20:55:35,155 Processing page 11
2022-11-07 20:56:13,224 Processing page 12
2022-11-07 20:56:51,889 Processing page 13
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-43: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '305'), ('id', 'MTS2085397')])"
Arguments: ()
2022-11-07 20:57:23,733 Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '305'), ('id', 'MTS2085397')])
2022-11-07 20:57:30,115 Processing page 14
2022-11-07 20:58:08,793 Processing page 15
2022-11-07 20:58:46,640 Processing page 16
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 65-69: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught SdGOIAM OG Goo 20) &>\\o94 \u0d2a\u0d3f\u0d33\u0d4d\u0d33 OrderedDict([('number', '410'), ('id', 'KL/18/122/240654'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d2a\u0d4d\\u200c]')])"
Arguments: ()
2022-11-07 20:58:59,754 Split uncaught SdGOIAM OG Goo 20) &>\o94 \u0d2a\u0d3f\u0d33\u0d4d\u0d33 OrderedDict([('number', '410'), ('id', 'KL/18/122/240654'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d2a\u0d4d\u200c]')])
2022-11-07 20:59:23,342 Processing page 17
2022-11-07 21:00:00,541 Processing page 18
2022-11-07 21:00:37,548 Processing page 19
2022-11-07 21:01:14,031 Processing page 20
2022-11-07 21:01:52,856 Processing page 21
2022-11-07 21:02:31,796 Processing page 22
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 52: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught adomalod said\u2019 eererd enfleg> OrderedDict([('number', '582'), ('id', 'ZPX0084095'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d37\u0d46\u0d31\u0d3f\u0d28\u0d4d\\u200d')])"
Arguments: ()
2022-11-07 21:02:56,234 Split uncaught adomalod said\u2019 eererd enfleg> OrderedDict([('number', '582'), ('id', 'ZPX0084095'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d37\u0d46\u0d31\u0d3f\u0d28\u0d4d\u200d')])
2022-11-07 21:03:10,132 Processing page 23
2022-11-07 21:03:48,558 Processing page 24
2022-11-07 21:04:27,085 Processing page 25
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 123-126: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught adomalag said erent enfleg> OrderedDict([('number', '666'), ('id', 'MTS2355956'), ('\u0d2a\u0d47\u0d30\u0d4d', '1]')])"
Arguments: ()
2022-11-07 21:04:59,057 Split uncaught adomalag said erent enfleg> OrderedDict([('number', '666'), ('id', 'MTS2355956'), ('\u0d2a\u0d47\u0d30\u0d4d', '1]')])
2022-11-07 21:05:05,979 Processing page 26
2022-11-07 21:05:45,127 Processing page 27
2022-11-07 21:05:57,511 Processing page 28
2022-11-07 21:06:08,297 Processing page 29
2022-11-07 21:06:25,788 Processing page 30
2022-11-07 21:06:28,585 Processing page 31
2022-11-07 21:06:28,807 Processing page 32
2022-11-07 21:06:29,026 Processing page 33
2022-11-07 21:06:29,081 Formatting and exporting data/part232/in/kerala/2015/2015_117_081.pdf data..
2022-11-07 21:06:29,128 Converted to csv: data/out/kerala/2015/2015_117_081.csv
2022-11-07 21:06:29,144 Converting data/part232/in/kerala/2015/2015_117_082.pdf to img...
2022-11-07 21:06:42,356 Parsing first and last page data..
2022-11-07 21:06:47,483 Detecting and parsing data/part232/in/kerala/2015/2015_117_082.pdf boxes..
2022-11-07 21:06:47,483 Processing page 3
2022-11-07 21:07:24,772 Processing page 4
2022-11-07 21:08:01,390 Processing page 5
2022-11-07 21:08:39,204 Processing page 6
2022-11-07 21:08:45,794 Processing page 7
2022-11-07 21:09:22,239 Processing page 8
2022-11-07 21:09:59,206 Processing page 9
2022-11-07 21:10:35,911 Processing page 10
2022-11-07 21:11:14,862 Processing page 11
2022-11-07 21:11:52,681 Processing page 12
2022-11-07 21:12:40,969 Processing page 13
2022-11-07 21:13:18,383 Processing page 14
2022-11-07 21:13:21,326 Processing page 15
2022-11-07 21:14:00,559 Processing page 16
2022-11-07 21:14:38,824 Processing page 17
2022-11-07 21:15:16,840 Processing page 18
2022-11-07 21:15:55,396 Processing page 19
2022-11-07 21:16:33,570 Processing page 20
2022-11-07 21:17:11,690 Processing page 21
2022-11-07 21:17:50,128 Processing page 22
2022-11-07 21:18:27,045 Processing page 23
2022-11-07 21:19:04,443 Processing page 24
2022-11-07 21:19:42,815 Processing page 25
2022-11-07 21:20:20,860 Processing page 26
2022-11-07 21:20:57,767 Processing page 27
2022-11-07 21:21:34,268 Processing page 28
2022-11-07 21:22:11,354 Processing page 29
2022-11-07 21:22:49,959 Processing page 30
2022-11-07 21:23:29,845 Processing page 31
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 53: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught sdomalodg suid\u2019 O2Dk> 94 \u0d2a\u0d3f\u0d33\u0d4d\u0d33 OrderedDict([('number', '790'), ('id', 'KL/18/122/261268'), ('\u0d2a\u0d47\u0d30\u0d4d', 'mowan')])"
Arguments: ()
2022-11-07 21:24:04,019 Split uncaught sdomalodg suid\u2019 O2Dk> 94 \u0d2a\u0d3f\u0d33\u0d4d\u0d33 OrderedDict([('number', '790'), ('id', 'KL/18/122/261268'), ('\u0d2a\u0d47\u0d30\u0d4d', 'mowan')])
2022-11-07 21:24:07,310 Processing page 32
2022-11-07 21:24:45,341 Processing page 33
2022-11-07 21:25:22,710 Processing page 34
2022-11-07 21:25:59,479 Processing page 35
2022-11-07 21:26:34,226 Processing page 36
2022-11-07 21:27:11,143 Processing page 37
2022-11-07 21:27:47,900 Processing page 38
2022-11-07 21:28:25,676 Processing page 39
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 65-69: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught SdGOIAM OG Goo 20) &>\\o94 \u0d2a\u0d3f\u0d33\u0d4d\u0d33 OrderedDict([('number', '1047'), ('id', 'KL/18/122/261339'), ('\u0d2a\u0d47\u0d30\u0d4d', 'qamrcaail')])"
Arguments: ()
2022-11-07 21:28:41,429 Split uncaught SdGOIAM OG Goo 20) &>\o94 \u0d2a\u0d3f\u0d33\u0d4d\u0d33 OrderedDict([('number', '1047'), ('id', 'KL/18/122/261339'), ('\u0d2a\u0d47\u0d30\u0d4d', 'qamrcaail')])
2022-11-07 21:29:04,007 Processing page 40
2022-11-07 21:29:42,695 Processing page 41
2022-11-07 21:30:21,271 Processing page 42
2022-11-07 21:30:59,188 Processing page 43
2022-11-07 21:31:36,654 Processing page 44
2022-11-07 21:32:13,401 Processing page 45
2022-11-07 21:32:53,568 Processing page 46
2022-11-07 21:33:32,283 Processing page 47
2022-11-07 21:34:10,899 Processing page 48
2022-11-07 21:34:49,385 Processing page 49
2022-11-07 21:35:29,087 Processing page 50
2022-11-07 21:36:07,757 Processing page 51
2022-11-07 21:36:46,962 Processing page 52
2022-11-07 21:37:24,885 Processing page 53
2022-11-07 21:38:02,666 Processing page 54
2022-11-07 21:38:20,558 Processing page 55
2022-11-07 21:38:27,856 Processing page 56
2022-11-07 21:38:29,816 Processing page 57
2022-11-07 21:38:39,903 Processing page 58
2022-11-07 21:38:53,778 Processing page 59
2022-11-07 21:39:12,836 Processing page 60
2022-11-07 21:39:46,354 Processing page 61
2022-11-07 21:40:10,634 Processing page 62
2022-11-07 21:40:14,852 Processing page 63
2022-11-07 21:40:16,173 Processing page 64
2022-11-07 21:40:22,466 Processing page 65
2022-11-07 21:40:22,699 Processing page 66
/share/svasudevan2lab/gs-delhi/parse_unsearchable_rolls/scripts/kerala/joblist_2015/kerala232.sh: line 1: 19028 Killed                  python scripts/kerala/kerala_2015.py data/part232/

#################
Epilogue Job Info:
Job ID: 466875[232].acropolis
User ID: t-9adar
Job Name: Kerala2015JobArray-232
Resource List: nodes=1:ppn=1,mem=3gb,neednodes=1:ppn=1
Resources Used: cput=01:06:59,vmem=3782388kb,walltime=01:08:13,mem=2821868kb,energy_used=0
Exit Code: 137
Exit code 137 job terminated, resource limit violation
Generally this means you need to request more RAM or CPU
Please compare your resources used/requested
#################

