2022-11-03 11:14:33,458 Converting data/part118/in/kerala/2016/2016_062_049.pdf to img...
2022-11-03 11:14:41,300 Parsing first and last page data..
2022-11-03 11:14:45,228 Detecting and parsing data/part118/in/kerala/2016/2016_062_049.pdf boxes..
2022-11-03 11:14:45,228 Processing page 3
2022-11-03 11:15:16,534 Processing page 4
2022-11-03 11:15:52,724 Processing page 5
2022-11-03 11:16:29,677 Processing page 6
2022-11-03 11:17:07,337 Processing page 7
2022-11-03 11:17:44,713 Processing page 8
2022-11-03 11:18:21,930 Processing page 9
2022-11-03 11:18:58,999 Processing page 10
2022-11-03 11:19:35,772 Processing page 11
2022-11-03 11:20:13,514 Processing page 12
2022-11-03 11:20:50,131 Processing page 13
2022-11-03 11:21:27,102 Processing page 14
2022-11-03 11:22:04,811 Processing page 15
2022-11-03 11:22:41,633 Processing page 16
2022-11-03 11:23:19,510 Processing page 17
2022-11-03 11:23:56,435 Processing page 18
2022-11-03 11:24:33,305 Processing page 19
2022-11-03 11:25:12,462 Processing page 20
2022-11-03 11:25:50,161 Processing page 21
2022-11-03 11:26:26,431 Processing page 22
2022-11-03 11:27:03,239 Processing page 23
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 123-126: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught adomraiog cod 1} T 3 B>YDIS OrderedDict([('number', '613'), ('id', 'MHQ1634955'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d2a\u0d3f]')])"
Arguments: ()
2022-11-03 11:27:30,129 Split uncaught adomraiog cod 1} T 3 B>YDIS OrderedDict([('number', '613'), ('id', 'MHQ1634955'), ('\u0d2a\u0d47\u0d30\u0d4d', '\u0d2a\u0d3f]')])
2022-11-03 11:27:40,342 Processing page 24
2022-11-03 11:28:17,773 Processing page 25
2022-11-03 11:28:53,350 Processing page 26
2022-11-03 11:29:18,752 Processing page 27
2022-11-03 11:29:57,160 Processing page 28
2022-11-03 11:30:34,807 Processing page 29
2022-11-03 11:31:10,725 Processing page 30
2022-11-03 11:31:45,977 Processing page 31
2022-11-03 11:32:23,759 Processing page 32
2022-11-03 11:33:01,917 Processing page 33
2022-11-03 11:33:39,739 Processing page 34
2022-11-03 11:34:16,035 Processing page 35
2022-11-03 11:34:51,760 Processing page 36
2022-11-03 11:35:27,995 Processing page 37
2022-11-03 11:36:05,676 Processing page 38
--- Logging error ---
Traceback (most recent call last):
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 39-43: ordinal not in range(256)
Call stack:
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/home/t-9adar/.conda/envs/env38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../parse_unsearchable_rolls/parser/parser.py", line 320, in get_data
    processed_box = self.process_boxes_text(text)
  File "../parse_unsearchable_rolls/parser/parser.py", line 149, in process_boxes_text
    result, last_key, is_splitted = self.columns_split(r, self.columns, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 255, in columns_split
    result, last_key, is_splitted = self.handle_separator_without_column(r, result, last_key)
  File "../parse_unsearchable_rolls/parser/parser.py", line 226, in handle_separator_without_column
    logging.warning(f'Split uncaught {r} {result}')
Message: "Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '1048'), ('id', 'KL/08/056/108328')])"
Arguments: ()
2022-11-03 11:36:39,880 Split uncaught \u0d2a\u0d47\u0d30\u0d4d\u200c =) OrderedDict([('number', '1048'), ('id', 'KL/08/056/108328')])
2022-11-03 11:36:42,987 Processing page 39
2022-11-03 11:37:20,259 Processing page 40
2022-11-03 11:37:56,359 Processing page 41
2022-11-03 11:38:34,145 Processing page 42
/share/svasudevan2lab/gs-delhi/parse_unsearchable_rolls/scripts/kerala/joblist_2016/kerala118.sh: line 1:  1038 Killed                  python scripts/kerala/kerala_2016.py data/part118/

#################
Epilogue Job Info:
Job ID: 466350[118].acropolis
User ID: t-9adar
Job Name: Kerala2016JobArray-118
Resource List: nodes=1:ppn=1,mem=2gb,neednodes=1:ppn=1
Resources Used: cput=00:23:28,vmem=3392492kb,walltime=00:24:26,mem=1998492kb,energy_used=0
Exit Code: 137
Exit code 137 job terminated, resource limit violation
Generally this means you need to request more RAM or CPU
Please compare your resources used/requested
#################

